### ISSUE TITLE
ERROR  There are no commands defined in the "generate" namespace.

### ISSUE THREAD

**Issue by jechaviz** [naranarethiya/laravel-model-resource-generator#1]
Steps:
`
composer require naranarethiya/model-resource-generator
php artisan generate:api-resources
`
I get:
`
ERROR  There are no commands defined in the "generate" namespace.
`

Other info:
`
Windows 10
laravel 10.24
`

**Comment by naranarethiya** [comment]
@jechaviz fixed issue, i have missed laravel auto-discovery in composer.json
Please update the package version to 0.0.3 and try.
